---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: default
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.93.0
  config: 
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    
    processors:
      batch: {}
    
    exporters:
      zipkin:
        endpoint: http://zipkin:9411/api/v2/spans
      
      logging:
        loglevel: debug
      
      prometheus:
        endpoint: "0.0.0.0:8889"
        enable_open_metrics: true
        const_labels:
          label1: value1
      
      otlphttp/loki:
        endpoint: http://loki:3100/otlp
        tls:
          insecure: true
    
    service:
      telemetry:
        metrics:
          address: ":8890"
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [zipkin]
        
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus, logging]
        
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/loki, logging]

---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: otlp-http
    port: 4318
    targetPort: 4318
  - name: prometheus
    port: 8889
    targetPort: 8889
  selector:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/name: otel-collector-collector